### ISSUE TITLE
No such property: scope for class: com.android.build.gradle.internal.variant.ApplicationVariantData

### ISSUE THREAD

**Issue by liuqingdada** [Omooo/Lavender#1]
android gradle build tool 4.1.2    不兼容

另外：插件没有处理LibraryVariant的情况，只处理了ApplicationVariant的情况吧

**Comment by Omooo** [comment]
好的，谢谢反馈，回去的时候我看一下～




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Omooo/Lavender"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月12日(星期五) 下午4:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Omooo/Lavender] No such property: scope for class: com.android.build.gradle.internal.variant.ApplicationVariantData (#1)





 
android gradle build tool 4.1.2    不兼容
 
另外：插件没有处理LibraryVariant的情况，只处理了ApplicationVariant的情况吧

**Comment by Omooo** [comment]
你好～
虽迟但到！现在已经适配到 AGP 7.2.4 版本了～
