### ISSUE TITLE
请问 cwebp 这个产物是怎么编译的呢？

### ISSUE THREAD

**Issue by siyehua** [Omooo/Lavender#2]
我把工程里的这个 cwebp 下载下来，发现是 x86 的，我们有的同事是 m1 芯片，需要再编译一个 arm 的。请问要怎么编译？

从官网上推荐的安装 brew 是可以，但是需要每个人都设置。通过你这个打包成一个完成的 unix 可执行文件才行。

所以我想再编译出一个 arm 芯片的。谢谢

**Comment by Omooo** [comment]
哦哦您好，可能之前写的时候并没有支持 m1，所以你可以从官方文档上面去下载对应的 cwebp：
https://developers.google.com/speed/webp/download
<img width="885" alt="image" src="https://user-images.githubusercontent.com/18626412/170623113-741f065a-e46e-43ba-b007-aa8dfb854446.png">
这里也就需要改 WebpToolUtil.kt 里面实现了，来判断是 mac arm 还是 x86 了～

**Comment by siyehua** [comment]
> 哦哦您好，可能之前写的时候并没有支持 m1，所以你可以从官方文档上面去下载对应的 cwebp： https://developers.google.com/speed/webp/download <img alt="image" width="885" src="https://user-images.githubusercontent.com/18626412/170623113-741f065a-e46e-43ba-b007-aa8dfb854446.png"> 这里也就需要改 WebpToolUtil.kt 里面实现了，来判断是 mac arm 还是 x86 了～

官网那个是动态链接库的，还需要安装什么 lib,jpg 啥的。。。我安装它的教程编译出来的也需要安装额外的东西，但是你的这个产物就不需要。所以特地请教你怎么把所有的东西都打到 cdwep 里面的

**Comment by Omooo** [comment]
你应该只需要把 bin 文件下面的 cwebp 可执行文件 copy 出来就行了：
<img width="432" alt="image" src="https://user-images.githubusercontent.com/18626412/170623976-ab60c10c-fdc7-4fe9-80cb-74e680ab6067.png">

**Comment by siyehua** [comment]
> 你应该只需要把 bin 文件下面的 cwebp 可执行文件 copy 出来就行了： <img alt="image" width="432" src="https://user-images.githubusercontent.com/18626412/170623976-ab60c10c-fdc7-4fe9-80cb-74e680ab6067.png">

![wecom-temp-e8e09728631b31e85cb6c0ce529e9c12](https://user-images.githubusercontent.com/9376247/170624375-05902483-db42-49b6-9b9a-0207a3a8423b.png)

直接拷贝出来，会提示这些，说白了还是要我先用 brew 安装这几个依赖。但是这样使用这个插件的成本就很高了，还要别的同事安装 brew，安装什么的。。。。

**Comment by Omooo** [comment]
好像还真有问题，我试了一下可以压缩图片，但是压缩后的图片无法打开了...
<img width="731" alt="image" src="https://user-images.githubusercontent.com/18626412/170626811-794eba59-9dbd-41e8-a7c6-4a5f704e40f0.png">

**Comment by Omooo** [comment]
神奇了，我的就是 M1 芯片，是可以用的呀：

**Comment by Omooo** [comment]
![image](https://user-images.githubusercontent.com/18626412/206609699-7cb18f2d-4d27-43ef-924f-53a47ddfa3b0.png)

**Comment by Omooo** [comment]
我看了下 booster，只有不同 Mac 版本的 cwebp 工具：https://github.com/didi/booster/blob/master/booster-task-compression-cwebp/src/main/resources/bin/macosx/10.12/cwebp
![image](https://user-images.githubusercontent.com/18626412/206609854-2450c780-c13b-41f0-b148-adbd1ba53daa.png)
