### ISSUE TITLE
最新的feat：适配AGP8.2的提交中删除了CwebpCompressTask相关的代码，是还不兼容吗？

### ISSUE THREAD

**Issue by NCdong** [Omooo/Lavender#88]
请问一下，打包自动 png 转 webp、webp 图片压缩相关代码在适配AGP8.2的提交中删除，是还不兼容吗？

**Comment by Omooo** [comment]
是的，AGP8.0 已经不能再处理中间产物了，Booster 里也删除了相关的 Task 了。
